# Generated by Django 3.0.5 on 2021-07-10 20:09

import datetime
import django.core.validators
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auditor_id', models.IntegerField()),
                ('commune_id', models.IntegerField()),
                ('category_id', models.CharField(max_length=6)),
                ('audit_type_id', models.CharField(max_length=6)),
                ('service_type_id', models.CharField(max_length=6)),
                ('exit_timestamp', models.DateTimeField(max_length=100)),
                ('values', djongo.models.fields.JSONField()),
                ('metadata', djongo.models.fields.JSONField()),
                ('blocks', djongo.models.fields.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='AttZone',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True)),
                ('questions', djongo.models.fields.JSONField()),
                ('category', models.IntegerField()),
                ('for_form', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=10)),
                ('token', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('province_id', models.IntegerField()),
                ('region_zona_att', models.IntegerField()),
                ('region_crm', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CrmZone',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Datalist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lists', djongo.models.fields.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('blocks', djongo.models.fields.JSONField()),
                ('for_mobile', models.BooleanField(default=True)),
                ('category', models.CharField(max_length=100)),
                ('audit_type', models.CharField(max_length=100)),
                ('service_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FormTree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tree', djongo.models.fields.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='InfoPanel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(max_length=100)),
                ('auditor_id', models.IntegerField()),
                ('technician_id', models.IntegerField()),
                ('data_type', models.IntegerField()),
                ('auditor_name', models.CharField(max_length=200)),
                ('answer_id', models.IntegerField()),
                ('photos', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('route', djongo.models.fields.JSONField()),
                ('category', djongo.models.fields.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('region_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.IntegerField(blank=True)),
                ('options', djongo.models.fields.JSONField()),
                ('value', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=True)),
                ('category_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('region_ordinal', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('blocks', djongo.models.fields.JSONField()),
                ('category', models.CharField(max_length=50)),
                ('question_based', models.BooleanField(default=False)),
                ('for_api', models.BooleanField(default=False)),
                ('only_admin', models.BooleanField(default=False)),
                ('is_enumerated', models.BooleanField(default=False)),
                ('name_format', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=100)),
                ('enterprise_id', models.IntegerField()),
                ('category_id', models.IntegerField()),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('team_group_id', models.IntegerField()),
                ('last_audit_date', models.DateTimeField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('rut', models.CharField(max_length=10, unique=True)),
                ('_type', models.IntegerField(validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(1)])),
                ('access_token', models.CharField(blank=True, default='Null', max_length=255)),
                ('access_token_mobile', models.CharField(blank=True, default='Null', max_length=255)),
                ('last_login', models.DateTimeField(blank=True)),
                ('category_id', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
