version: "3.9" # version de docker-compose
services:
  db:
    networks:
      - app-network
    platform: linux/x86_64
    image: postgres:14
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
      - PGDATA=/var/lib/postgresql/data/proyectoTesting/
    ports:
      - "5432"
    volumes:
      - ./db:/var/lib/postgresql/data
  backend:
    platform: linux/x86_64
    build: ./
    ports:
      - "3000:3000"
    depends_on:
      - db
    command: rails s -e development -b 0.0.0.0 -p 3000
    env_file:
      - ./.env
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
    volumes:
      - ./:/app
    networks:
      - app-network


networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
