version: "3.9" # version de docker-compose
services:
  db:
    networks:
      - app-network
    platform: linux/x86_64
    image: postgis/postgis
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
    ports:
      - "5432"
    volumes:
      - ./db:/var/lib/postgresql/data
  backend:
    platform: linux/x86_64
    build: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - db
    command: rails s -b 0.0.0.0 -p 3000
    env_file:
      - ./backend/.env
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
    volumes:
      - ./backend:/backend
    networks:
      - app-network

  frontend:
    platform: linux/x86_64
    build: ./frontend
    ports:
      - "3001:3001"
    command: npm start
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    networks:
      - app-network

  nginx:
    platform: linux/x86_64
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    ports:
      - 80:80
      - 443:443
    depends_on:
      - backend
      - frontend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
