from backend_app.db_models.answer import Answers
from backend_app.db_models.block import Block
from backend_app.db_models.commune import Commune
from backend_app.db_models.enterprise import Enterprise
from backend_app.db_models.form import Form
from backend_app.db_models.form_tree import FormTree
from backend_app.db_models.metadata import Metadata
from backend_app.db_models.province import Province
from backend_app.db_models.question import Question
from backend_app.db_models.region import Region
from backend_app.db_models.report import Report
from backend_app.db_models.team import Team
from backend_app.db_models.technician import Technician
from backend_app.db_models.user import User
from backend_app.db_models.att_zone import AttZone
from backend_app.db_models.crmzone import CrmZone
from backend_app.db_models.datalist import Datalist
from backend_app.db_models.info_panel import InfoPanel
from backend_app.db_models.client import Client
