FROM python:3.8-slim
RUN apt-get update && apt-get install -y curl

ENV PYTHONFAULTHANDLER=1 \
  PYTHONUNBUFFERED=1 \
  PYTHONHASHSEED=random \
  PIP_NO_CACHE_DIR=off \
  PIP_DISABLE_PIP_VERSION_CHECK=on \
  PIP_DEFAULT_TIMEOUT=100


# Install poetry
RUN curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -

ENV PATH="${PATH}:/root/.poetry/bin"

WORKDIR /code
COPY poetry.lock pyproject.toml /code/
RUN poetry install

COPY . /code

# Remove .env file since we will overwrite it with docker compose
RUN rm -f /code/.env 2> /dev/null