version: '3.3'

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile.dev
    depends_on:
      - mongo
    command: poetry run osam_backend/manage.py runserver 0.0.0.0:8000

    environment:
      - B_MONGO_URI=mongodb://${MONGO_USER}:${MONGO_PW}@mongo/admin
    ports:
      - "8000:8000"
    volumes: 
      - .:/code
      
  mongo:
    image : mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PW}
    volumes:
      - mongodb_data:/data/db

  # Add a visual manager for mongo
  mongo-express:
    image: mongo-express
    depends_on:
      - mongo
    environment:
        - ME_CONFIG_MONGODB_SERVER=mongo
        - ME_CONFIG_MONGODB_PORT=27017
        - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
        - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
        - ME_CONFIG_MONGODB_AUTH_USERNAME=${MONGO_USER}
        - ME_CONFIG_MONGODB_AUTH_PASSWORD=${MONGO_PW}
        - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_USER}
        - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_PW}
 
    ports:
      - "8081:8081"

volumes:
  mongodb_data: